exports.PHASE_LOBBY = "PHASE_LOBBY";
exports.PHASE_REVEAL = "PHASE_REVEAL";
exports.PHASE_DAY = "PHASE_DAY";
exports.PHASE_VOTE = "PHASE_VOTE";
exports.PHASE_NIGHT = "PHASE_NIGHT";
exports.PHASE_END = "PHASE_END";

exports.CREATE_GAME = "CREATE_GAME";
exports.START_GAME = "START_GAME";
exports.JOIN_GAME = "JOIN_GAME";
exports.REVEAL_READY = "REVEAL_READY";
exports.NOMINATE = "NOMINATE";
exports.VOTE_YES = "VOTE_YES";
exports.VOTE_NO = "VOTE_NO";
exports.DEVOUR = "DEVOUR";
exports.UPDATE_STATE = "UPDATE_STATE";
exports.PLAYER_PRESENCE = "PLAYER_PRESENCE";

exports.WEREWOLF = "WEREWOLF";
exports.VILLAGER = "VILLAGER";

exports.PAGE_MENU = "PAGE_MENU";
exports.PAGE_HOST = "PAGE_HOST";
exports.PAGE_JOIN  = "PAGE_JOIN";
exports.PAGE_LOBBY = "PAGE_LOBBY";
exports.PAGE_REVEAL = "PAGE_REVEAL";
exports.PAGE_NIGHT = "PAGE_NIGHT";
exports.PAGE_VOTE = "PAGE_VOTE";
exports.PAGE_DAY = "PAGE_DAY";
exports.PAGE_END = "PAGE_END";

exports.ERROR = "ERROR";

exports.SHOW_HOST = "SHOW_HOST";
exports.SHOW_JOIN = "SHOW_JOIN";

exports.GAME_STATE_UPDATE = "GAME_STATE_UPDATE";
exports.CONNECTING = "CONNECTING";
exports.CONNECTED = "CONNECTED";
exports.HOST_GAME = "HOST_GAME";
exports.CANCEL = "CANCEL";
exports.CHOOSE_VICTIM = "CHOOSE_VICTIM";
